"""add_project_defaults

Revision ID: 6893952f5742
Revises: 7bd81dfc9cbf
Create Date: 2026-04-27 20:06:13.721939

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6893952f5742'
down_revision: Union[str, None] = '7bd81dfc9cbf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('project_defaults',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('default_tags', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_project_defaults_project_name'), 'project_defaults', ['project_name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_project_defaults_project_name'), table_name='project_defaults')
    op.drop_table('project_defaults')
    # ### end Alembic commands ###
