"""add_work_logs

Revision ID: 7bd81dfc9cbf
Revises: a4b5c6d7e8f9
Create Date: 2026-04-27 17:31:28.531444

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7bd81dfc9cbf'
down_revision: Union[str, None] = 'a4b5c6d7e8f9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('work_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('day_id', sa.Integer(), nullable=False),
    sa.Column('project_name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['day_id'], ['days.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_logs_day_id'), 'work_logs', ['day_id'], unique=False)
    op.create_table('work_log_tags',
    sa.Column('work_log_id', sa.Integer(), nullable=False),
    sa.Column('tag_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['work_log_id'], ['work_logs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('work_log_id', 'tag_id')
    )
    op.create_index('ix_work_log_tags_tag_id', 'work_log_tags', ['tag_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_work_log_tags_tag_id', table_name='work_log_tags')
    op.drop_table('work_log_tags')
    op.drop_index(op.f('ix_work_logs_day_id'), table_name='work_logs')
    op.drop_table('work_logs')
    # ### end Alembic commands ###
