"""make day_id and category nullable for backlog

Revision ID: dc68ad4bbc2b
Revises: b1c2d3e4f5a6
Create Date: 2026-02-24 18:34:54.028503

"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dc68ad4bbc2b'
down_revision: Union[str, None] = 'b1c2d3e4f5a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'day_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('tasks', 'category',
               existing_type=sa.String(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('tasks', 'category',
               existing_type=sa.String(),
               nullable=False)
    op.alter_column('tasks', 'day_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###
