"""Shared package for Oliver backend and MCP server."""

from oliver_shared.constants import (
    CATEGORY_DEEP_WORK,
    CATEGORY_MAINTENANCE,
    CATEGORY_SHORT_TASK,
    DEEP_WORK_GOAL_SECONDS,
    FOCUS_GOAL_KEY,
    MAX_TAGS_PER_TASK,
    RECURRING_DAYS_OFF_KEY,
    STATUS_COMPLETED,
    STATUS_GOAL_ACTIVE,
    STATUS_GOAL_COMPLETED,
    STATUS_IN_PROGRESS,
    STATUS_PENDING,
    STATUS_ROLLED_FORWARD,
    TIMER_DISPLAY_KEY,
    VALID_CATEGORIES,
    VALID_STATUSES,
    VALID_WEEKDAYS,
)
from oliver_shared.validation import normalize_tag_name, validate_tag_count

__all__ = [
    "CATEGORY_DEEP_WORK",
    "CATEGORY_MAINTENANCE",
    "CATEGORY_SHORT_TASK",
    "DEEP_WORK_GOAL_SECONDS",
    "FOCUS_GOAL_KEY",
    "MAX_TAGS_PER_TASK",
    "RECURRING_DAYS_OFF_KEY",
    "STATUS_COMPLETED",
    "STATUS_GOAL_ACTIVE",
    "STATUS_GOAL_COMPLETED",
    "STATUS_IN_PROGRESS",
    "STATUS_PENDING",
    "STATUS_ROLLED_FORWARD",
    "TIMER_DISPLAY_KEY",
    "VALID_CATEGORIES",
    "VALID_STATUSES",
    "VALID_WEEKDAYS",
    "normalize_tag_name",
    "validate_tag_count",
]
